# Generated by Django 5.1.4 on 2025-01-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_alter_employee_image_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='dd.png', null=True, upload_to=''),
        ),
    ]
