# Generated by Django 5.1.4 on 2025-01-13 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_alter_checkinout_date_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 8, 8, 6, 114883, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
