# Generated by Django 5.1.4 on 2025-01-13 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_alter_checkinout_date_alter_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 10, 53, 8, 432247, tzinfo=datetime.timezone.utc)),
        ),
    ]
