# Generated by Django 5.1.4 on 2025-01-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_alter_task_employee_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent')], default='present', max_length=60),
        ),
    ]
