# Generated by Django 5.1.4 on 2025-01-15 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_alter_checkinout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 15)),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 5, 30, 14, 361975, tzinfo=datetime.timezone.utc)),
        ),
    ]
