# Generated by Django 5.1.4 on 2025-01-15 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0006_alter_attendance_date_alter_checkinout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 8, 10, 13, 26947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='fff@gmail.com', max_length=50),
        ),
    ]
