# Generated by Django 5.1.4 on 2025-01-03 05:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0007_checkinout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 3)),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 3)),
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_info', to='empapp.employee')),
            ],
        ),
    ]
