# Generated by Django 5.1.4 on 2025-01-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0012_alter_attendance_date_alter_checkinout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='employee',
        ),
    ]
