# Generated by Django 5.1.4 on 2025-01-08 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0015_post_disliked_by_post_liked_by_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 8)),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 8)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
