# Generated by Django 5.1.4 on 2025-01-09 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0016_alter_attendance_date_alter_checkinout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 9)),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 9)),
        ),
    ]
